import Preloader from "@/components/Preloader";
import DemoClient from "@/components/DemoClient";
import HowItWorks from "@/components/HowItWorks";

export default function Page() {
  return (
    <>
      <Preloader />
      <main className="shell">
        <span className="eyebrow">Live demo · token streaming</span>
        <h1 className="hero-title">
          Streaming vs <span className="grad">Non&#8209;streaming</span>
          <br />
          answers, side by side
        </h1>
        <p className="hero-sub">
          One question. The same sources from Azure AI Search and the same GPT&#8209;4.1 model.
          Watch the real difference between waiting for a full answer and seeing it stream in
          token by token.
        </p>

        <DemoClient />
        <HowItWorks />

        <div className="footer">
          Grounded by Azure AI Search (Foundry IQ) · Generated by Azure OpenAI GPT&#8209;4.1 ·
          Running on Azure Container Apps
        </div>
      </main>
    </>
  );
}
